---
env:
  - NO_TOOL_CHECK=True STORAGE=file
  - NO_TOOL_CHECK=True STORAGE=s3minioCs
language: go
sudo: required
services:
  - docker
go:
  - 1.7.x
  - 1.8.x
  - master
os:
  - linux
script:
  - go get
  - make pgglaskugel
  - make tarball
  - make test
  - cd tools/Test-CentOS7; ./run_test_in_docker.sh $STORAGE
